// ===========================================================================
// VA 0x0047C0A0 - HandleWindowPaint  (original: sub_47C0A0, 10225 bytes)
// ===========================================================================
// WM_PAINT handler (sole caller: WndProc 0x004C3A10 @ 0x4C3A79).
//
// Draws the panel chrome and static labels of the main window with GDI,
// blits the three offscreen UI layers, then - AFTER EndPaint - runs the
// frame driver (0x0046B090) when the render gate (this+672812) allows,
// and finally refreshes the bone-list scrollbar (control 427) from a
// SCROLLINFO embedded at this+2372.
//
// Offscreen layers blitted at the tail:
//   this+736   timeline strip  -> (6, 95)          w = sidebar-10  h = 50
//   this+724   main panel      -> (6, 145)         w = sidebar-25  h = bottom-393
//   this+744   interp curve    -> (8, bottom-135)  128x128
//
// Deviation note: the original repeats each label as a full 10-argument
// sub_40E290 (DrawGlyph) call; the port factors the invariable colour
// arguments (this+656852/53/54, flag 0) into a local Lbl() wrapper.
// Every call site keeps its exact string/size/coordinate arguments.
// =========================================================================//
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <Windows.h>

#include <cstdint>

#include "mikudancestudio/bottom_panel_layout.hpp"
#include "mikudancestudio/mmd_app.hpp"
#include "mikudancestudio/model.hpp"
#include "mikudancestudio/offsets.hpp"
#include "mikudancestudio/ported_funcs.hpp"

namespace mikudancestudio {
namespace {

// GENERATED by scripts/gen_wm_paint_labels.py - do not edit.
// Narrow Shift-JIS label bytes from .rdata (0x52ED84-0x52F090).
#include "wm_paint_labels.inc"

void Lbl(MMDApp* a, const char* s, HDC hdc, int size, int x, int y) {
    DrawGlyph(a, s, hdc, size, x, y,
              a->UiTextRed(), a->UiTextGreen(), a->UiTextBlue(), 0);
}

}  // namespace

void HandleWindowPaint(MMDApp* app) {
    HWND hwnd = static_cast<HWND>(app->Hwnd());
    PAINTSTRUCT ps;

    if (app->FullscreenMode() != 0) {
        BeginPaint(hwnd, &ps);
        EndPaint(hwnd, &ps);
        return;
    }

    RECT rc;
    GetClientRect(hwnd, &rc);
    HDC hdc = BeginPaint(hwnd, &ps);

    HPEN pen = CreatePen(0, 1,
        app->ThemeColor(UiThemeColor::WindowFill));
    HBRUSH brush = CreateSolidBrush(
        app->ThemeColor(UiThemeColor::WindowFill));
    HGDIOBJ oldPen = SelectObject(hdc, pen);
    HGDIOBJ oldBrush = SelectObject(hdc, brush);
    const int side = app->SidebarWidth();

    Rectangle(hdc, 0, 0, 3, rc.bottom - 160);
    Rectangle(hdc, 0, 0, side, 3);
    Rectangle(hdc, 0, 47, side, 50);
    Rectangle(hdc, side - 2, 0, side + 9, rc.bottom - 160);
    FillPanelBottom(hdc, 0, rc.bottom - 160, rc.right, rc.bottom,
        app->ThemeColor(UiThemeColor::WindowFill),
        app->ThemeColor(UiThemeColor::WindowBorder), 1);         // 0x40DF10
    SelectObject(hdc, oldBrush);
    DeleteObject(brush);
    SelectObject(hdc, oldPen);
    DeleteObject(pen);
    HandlePaletteChanged(hdc);                                    // 0x42CEB0

    HPEN black = CreatePen(0, 1, 0);
    SelectObject(hdc, black);
    MoveToEx(hdc, 3, 50, nullptr);
    LineTo(hdc, side - 3, 50);
    LineTo(hdc, side - 3, rc.bottom - 161);
    LineTo(hdc, 3, rc.bottom - 161);
    LineTo(hdc, 3, 50);
    MoveToEx(hdc, side - 4, 95, nullptr);
    LineTo(hdc, side - 4, 145);

    const bool en = app->EnglishUI() != 0;
    if (en) {
        Lbl(app, "frame manipulation", hdc, 12, side / 2 - 50, 51);
        Lbl(app, "-", hdc, 12, side / 2 + 55, rc.bottom - 198);
    } else {
        Lbl(app, kJpLblFrameManip, hdc, 12, side / 2 - 35, 51);
        Lbl(app, kJpLblWave, hdc, 12, side / 2 + 52, rc.bottom - 198);
    }

    if (app->FloatingWindow() == nullptr) {
        HBRUSH blk = CreateSolidBrush(0);
        SelectObject(hdc, blk);
        const int top = app->state.hideTop;
        if (top <= rc.top + 25) {
            Rectangle(hdc, side + 9, 0,
                      app->state.hideRight,
                      rc.bottom - 160);
            Rectangle(hdc, app->state.hideLeft, 0,
                      rc.right, rc.bottom - 160);
        } else {
            Rectangle(hdc, side + 9, 0, rc.right, top - 25);
            Rectangle(hdc, side + 9,
                      app->state.hideBottom + 32,
                      rc.right, rc.bottom - 160);
        }
        SelectObject(hdc, oldBrush);
        DeleteObject(blk);
    }

    if (en) {
        Lbl(app, "Interpolation curve", hdc, 12, 60, rc.bottom - 155);
        Lbl(app, "auto", hdc, 12, 160, rc.bottom - 104);
    } else {
        Lbl(app, kJpLblInterpCurve, hdc, 12, 70, rc.bottom - 155);
        Lbl(app, kJpLblAutoSet, hdc, 12, 160, rc.bottom - 104);
    }

    HBRUSH gray = CreateSolidBrush(0x00DCDCDC);
    SelectObject(hdc, gray);
    Rectangle(hdc, side, 0, side + 6, rc.bottom - 159);
    SelectObject(hdc, oldPen);
    DeleteObject(black);
    SelectObject(hdc, oldBrush);
    DeleteObject(gray);

    if (en)
        Lbl(app, "bone/frame manipulation", hdc, 12, side / 2 - 70, 7);
    else
        Lbl(app, kJpLblBoneFrameManip, hdc, 12, side / 2 - 55, 7);

    if (en) {
        Lbl(app, "model manipulation", hdc, 12, 238, rc.bottom - 155);
        Lbl(app, "disp", hdc, 12, 240, rc.bottom - 83);
    } else {
        Lbl(app, kJpLblModelManip, hdc, 12, 258, rc.bottom - 155);
        Lbl(app, kJpLblDisp, hdc, 12, 240, rc.bottom - 83);
    }
    Lbl(app, "ON", hdc, 12, 244, rc.bottom - 35);
    Lbl(app, kLabelOff, hdc, 12, 244, rc.bottom - 18);

    // --- manipulation-mode panel labels ----------------------------------
    // v9 accumulates the horizontal shift of the right-hand panels exactly
    // like the original (each active panel reserves its width).
    const BottomPanelLayout panelLayout = ComputeBottomPanelLayout(app);
    int v9 = panelLayout.leading;
    if (app->state.optflag0 != 0) {
        if (app->state.optflag1 != 0) {
            if (en) {
                Lbl(app, "camera", hdc, 12, 423, rc.bottom - 155);
                Lbl(app, "view angle ", hdc, 11, 368, rc.bottom - 107);
                Lbl(app, "follow bone", hdc, 11, 368, rc.bottom - 67);
            } else {
                Lbl(app, kJpLblCameraManip, hdc, 12, 410, rc.bottom - 155);
                Lbl(app, kJpLblViewAngle, hdc, 11, 368, rc.bottom - 107);
                Lbl(app, kJpLblFollowBone, hdc, 11, 368, rc.bottom - 67);
            }
        } else {
            if (en) {
                Lbl(app, "c", hdc, 12, 368, rc.bottom - 130);
                Lbl(app, "a", hdc, 12, 368, rc.bottom - 110);
                Lbl(app, "m", hdc, 12, 366, rc.bottom - 90);
                Lbl(app, "e", hdc, 12, 368, rc.bottom - 70);
                Lbl(app, "r", hdc, 12, 369, rc.bottom - 50);
                Lbl(app, "a", hdc, 12, 368, rc.bottom - 30);
            } else {
                Lbl(app, kJpLblKa, hdc, 12, 365, rc.bottom - 130);
                Lbl(app, kJpLblMe, hdc, 12, 365, rc.bottom - 110);
                Lbl(app, kJpLblRa, hdc, 12, 365, rc.bottom - 90);
                Lbl(app, kJpLblSou, hdc, 12, 364, rc.bottom - 70);
                Lbl(app, kJpLblSaku, hdc, 12, 364, rc.bottom - 50);
            }
        }
    } else if (app->state.optflag4 != 0) {
        if (en)
            Lbl(app, "bone manipulation", hdc, 12, 413, rc.bottom - 155);
        else
            Lbl(app, kJpLblBoneManip, hdc, 12, 425, rc.bottom - 155);
    } else {
        if (en) {
            Lbl(app, "b", hdc, 12, 367, rc.bottom - 130);
            Lbl(app, "o", hdc, 12, 367, rc.bottom - 110);
            Lbl(app, "n", hdc, 12, 367, rc.bottom - 90);
            Lbl(app, "e", hdc, 12, 367, rc.bottom - 70);
        } else {
            Lbl(app, kJpLblBo, hdc, 12, 364, rc.bottom - 130);
            Lbl(app, kJpLblBar, hdc, 12, 364, rc.bottom - 110);
            Lbl(app, kJpLblN, hdc, 12, 365, rc.bottom - 90);
            Lbl(app, kJpLblSou, hdc, 12, 364, rc.bottom - 70);
            Lbl(app, kJpLblSaku, hdc, 12, 364, rc.bottom - 50);
        }
    }

    // light panel (only reachable in camera mode, mirrors the original)
    if (app->state.optflag0 != 0) {
        if (app->state.optflag2 != 0) {
            if (en) {
                Lbl(app, "light manipulation", hdc, 12, 548 - v9, rc.bottom - 155);
                Lbl(app, "R", hdc, 12, 502 - v9, rc.bottom - 137);
                Lbl(app, "G", hdc, 12, 502 - v9, rc.bottom - 119);
                Lbl(app, "B", hdc, 12, 502 - v9, rc.bottom - 101);
                Lbl(app, "X", hdc, 12, 502 - v9, rc.bottom - 81);
                Lbl(app, "Y", hdc, 12, 502 - v9, rc.bottom - 63);
                Lbl(app, "Z", hdc, 12, 502 - v9, rc.bottom - 45);
            } else {
                Lbl(app, kJpLblLightManip, hdc, 12, 563 - v9, rc.bottom - 155);
                Lbl(app, kJpLblAka, hdc, 12, 503 - v9, rc.bottom - 137);
                Lbl(app, kJpLblMidori, hdc, 12, 503 - v9, rc.bottom - 119);
                Lbl(app, kJpLblAo, hdc, 12, 503 - v9, rc.bottom - 101);
                Lbl(app, kJpLblX, hdc, 12, 504 - v9, rc.bottom - 81);
                Lbl(app, kJpLblY, hdc, 12, 505 - v9, rc.bottom - 63);
                Lbl(app, kJpLblZ, hdc, 12, 505 - v9, rc.bottom - 45);
            }
        } else {
            if (en) {
                Lbl(app, "l", hdc, 12, 505 - v9, rc.bottom - 130);
                Lbl(app, "i", hdc, 12, 505 - v9, rc.bottom - 110);
                Lbl(app, "g", hdc, 12, 504 - v9, rc.bottom - 90);
                Lbl(app, "h", hdc, 12, 504 - v9, rc.bottom - 70);
                Lbl(app, "t", hdc, 12, 505 - v9, rc.bottom - 50);
            } else {
                Lbl(app, kJpLblShou, hdc, 12, 502 - v9, rc.bottom - 130);
                Lbl(app, kJpLblMei, hdc, 12, 502 - v9, rc.bottom - 110);
                Lbl(app, kJpLblSou, hdc, 12, 502 - v9, rc.bottom - 90);
                Lbl(app, kJpLblSaku, hdc, 12, 502 - v9, rc.bottom - 70);
            }
        }
    } else if (app->state.optflag5 != 0) {
        // facial panel
        if (en) {
            Lbl(app, "facial manipulation", hdc, 12, 683 - v9, rc.bottom - 155);
            Lbl(app, "eyes", hdc, 12, 606 - v9, rc.bottom - 137);
            Lbl(app, "brow", hdc, 12, 606 - v9, rc.bottom - 67);
            Lbl(app, "mouth", hdc, 12, 736 - v9, rc.bottom - 137);
            Lbl(app, "other", hdc, 12, 736 - v9, rc.bottom - 67);
        } else {
            Lbl(app, kJpLblFacialManip, hdc, 12, 703 - v9, rc.bottom - 155);
            Lbl(app, kJpLblMe2, hdc, 12, 606 - v9, rc.bottom - 137);
            Lbl(app, kJpLblMayu, hdc, 12, 606 - v9, rc.bottom - 67);
            Lbl(app, kJpLblLip, hdc, 12, 736 - v9, rc.bottom - 137);
            Lbl(app, kJpLblSonota, hdc, 12, 736 - v9, rc.bottom - 67);
        }
    } else {
        if (en) {
            Lbl(app, "f", hdc, 12, 602 - v9, rc.bottom - 130);
            Lbl(app, "a", hdc, 12, 601 - v9, rc.bottom - 110);
            Lbl(app, "c", hdc, 12, 601 - v9, rc.bottom - 90);
            Lbl(app, "e", hdc, 12, 601 - v9, rc.bottom - 70);
        } else {
            Lbl(app, kJpLblHyou, hdc, 12, 599 - v9, rc.bottom - 130);
            Lbl(app, kJpLblJou, hdc, 12, 599 - v9, rc.bottom - 110);
            Lbl(app, kJpLblSou, hdc, 12, 599 - v9, rc.bottom - 90);
            Lbl(app, kJpLblSaku, hdc, 12, 599 - v9, rc.bottom - 70);
        }
    }
    v9 = panelLayout.afterLightOrFace;

    // self-shadow panel
    if (app->state.optflag0 != 0) {
        if (app->state.optflag6 != 0) {
            if (en) {
                Lbl(app, "self_shadow manipulation", hdc, 12, 708 - v9, rc.bottom - 155);
                Lbl(app, "shadow range", hdc, 12, 690 - v9, rc.bottom - 95);
                Lbl(app, "detail", hdc, 12, 690 - v9, rc.bottom - 54);
                Lbl(app, "far", hdc, 12, 840 - v9, rc.bottom - 54);
            } else {
                Lbl(app, kJpLblSelfShadow, hdc, 12, 733 - v9, rc.bottom - 155);
                Lbl(app, kJpLblShadowRange, hdc, 12, 690 - v9, rc.bottom - 100);
                Lbl(app, kJpLblKirei, hdc, 12, 690 - v9, rc.bottom - 53);
                Lbl(app, kJpLblEnpou, hdc, 12, 830 - v9, rc.bottom - 53);
            }
        } else {
            if (en) {
                Lbl(app, "s", hdc, 12, 688 - v9, rc.bottom - 130);
                Lbl(app, "s", hdc, 12, 688 - v9, rc.bottom - 109);
                Lbl(app, "h", hdc, 12, 688 - v9, rc.bottom - 96);
                Lbl(app, "a", hdc, 12, 688 - v9, rc.bottom - 83);
                Lbl(app, "d", hdc, 12, 688 - v9, rc.bottom - 70);
                Lbl(app, "o", hdc, 12, 688 - v9, rc.bottom - 57);
                Lbl(app, "w", hdc, 12, 687 - v9, rc.bottom - 44);
            } else {
                Lbl(app, kJpLblSe, hdc, 12, 685 - v9, rc.bottom - 130);
                Lbl(app, kJpLblRu, hdc, 12, 685 - v9, rc.bottom - 110);
                Lbl(app, kJpLblFu, hdc, 12, 685 - v9, rc.bottom - 90);
                Lbl(app, kJpLblKage, hdc, 12, 685 - v9, rc.bottom - 70);
                Lbl(app, kJpLblSou, hdc, 12, 685 - v9, rc.bottom - 50);
                Lbl(app, kJpLblSaku, hdc, 12, 685 - v9, rc.bottom - 30);
            }
        }
    }
    v9 = panelLayout.afterSelfShadow;

    // accessory panel
    if (app->state.optflag0 != 0) {
        v9 = panelLayout.accessory;
        if (app->state.optflag3 != 0) {
            if (en) {
                Lbl(app, "accessory manipulation", hdc, 12, 723 - v9, rc.bottom - 155);
                Lbl(app, "X", hdc, 12, 686 - v9, rc.bottom - 68);
                Lbl(app, "Y", hdc, 12, 749 - v9, rc.bottom - 68);
                Lbl(app, "Z", hdc, 12, 812 - v9, rc.bottom - 68);
                Lbl(app, "Rx", hdc, 12, 684 - v9, rc.bottom - 48);
                Lbl(app, "Ry", hdc, 12, 747 - v9, rc.bottom - 48);
                Lbl(app, "Rz", hdc, 12, 810 - v9, rc.bottom - 48);
                Lbl(app, "Si", hdc, 12, 687 - v9, rc.bottom - 28);
                Lbl(app, "Tr", hdc, 12, 747 - v9, rc.bottom - 28);
                Lbl(app, "display", hdc, 12, 837 - v9, rc.bottom - 141);
                Lbl(app, "shadow", hdc, 12, 837 - v9, rc.bottom - 126);
            } else {
                Lbl(app, kJpLblAccManip, hdc, 12, 738 - v9, rc.bottom - 155);
                Lbl(app, kJpLblX, hdc, 12, 685 - v9, rc.bottom - 68);
                Lbl(app, kJpLblY, hdc, 12, 748 - v9, rc.bottom - 68);
                Lbl(app, kJpLblZ, hdc, 12, 811 - v9, rc.bottom - 68);
                Lbl(app, "Rx", hdc, 12, 683 - v9, rc.bottom - 48);
                Lbl(app, "Ry", hdc, 12, 746 - v9, rc.bottom - 48);
                Lbl(app, "Rz", hdc, 12, 809 - v9, rc.bottom - 48);
                Lbl(app, "Si", hdc, 12, 684 - v9, rc.bottom - 28);
                Lbl(app, "Tr", hdc, 12, 747 - v9, rc.bottom - 28);
                Lbl(app, kJpLblDisp, hdc, 12, 840 - v9, rc.bottom - 141);
                Lbl(app, kJpLblKage, hdc, 12, 840 - v9, rc.bottom - 126);
            }
        } else {
            if (en) {
                Lbl(app, "a", hdc, 12, 688 - v9, rc.bottom - 130);
                Lbl(app, "c", hdc, 12, 688 - v9, rc.bottom - 117);
                Lbl(app, "c", hdc, 12, 688 - v9, rc.bottom - 104);
                Lbl(app, "e", hdc, 12, 688 - v9, rc.bottom - 91);
                Lbl(app, "s", hdc, 12, 688 - v9, rc.bottom - 78);
                Lbl(app, "s", hdc, 12, 688 - v9, rc.bottom - 65);
                Lbl(app, "o", hdc, 12, 688 - v9, rc.bottom - 52);
                Lbl(app, "r", hdc, 12, 689 - v9, rc.bottom - 39);
                Lbl(app, "y", hdc, 12, 688 - v9, rc.bottom - 26);
            } else {
                Lbl(app, kJpLblA, hdc, 12, 685 - v9, rc.bottom - 130);
                Lbl(app, kJpLblKu, hdc, 12, 685 - v9, rc.bottom - 115);
                Lbl(app, kJpLblSe, hdc, 12, 685 - v9, rc.bottom - 100);
                Lbl(app, kJpLblSa, hdc, 12, 685 - v9, rc.bottom - 85);
                Lbl(app, kJpLblRi, hdc, 12, 687 - v9, rc.bottom - 70);
                Lbl(app, kJpLblSou, hdc, 12, 685 - v9, rc.bottom - 55);
                Lbl(app, kJpLblSaku, hdc, 12, 685 - v9, rc.bottom - 40);
            }
        }
    }
    v9 = panelLayout.final;

    // viewpoint cluster
    if (en) {
        Lbl(app, "view", hdc, 12, 949 - v9, rc.bottom - 155);
        Lbl(app, "model", hdc, 12, 918 - v9, rc.bottom - 98);
        Lbl(app, "bone", hdc, 12, 988 - v9, rc.bottom - 98);
    } else {
        Lbl(app, kJpLblShiten, hdc, 12, 943 - v9, rc.bottom - 155);
        Lbl(app, kJpLblModel, hdc, 12, 918 - v9, rc.bottom - 98);
        Lbl(app, kJpLblBone, hdc, 12, 988 - v9, rc.bottom - 98);
    }

    // play controls
    if (en) {
        Lbl(app, "-", hdc, 12, 945 - v9, rc.bottom - 34);
        Lbl(app, "play", hdc, 12, 932 - v9, rc.bottom - 77);
        Lbl(app, "repeat", hdc, 10, 974 - v9, rc.bottom - 57);
        Lbl(app, "from flame", hdc, 10, 902 - v9, rc.bottom - 18);
        Lbl(app, "stop flame", hdc, 10, 967 - v9, rc.bottom - 18);
    } else {
        Lbl(app, kJpLblWave, hdc, 12, 939 - v9, rc.bottom - 34);
        Lbl(app, kJpLblPlay, hdc, 12, 929 - v9, rc.bottom - 77);
        Lbl(app, kJpLblRepeat, hdc, 10, 969 - v9, rc.bottom - 57);
        Lbl(app, kJpLblFlameStart, hdc, 10, 903 - v9, rc.bottom - 18);
        Lbl(app, kJpLblFlameStop, hdc, 10, 968 - v9, rc.bottom - 18);
    }
    if (en)
        Lbl(app, "vol", hdc, 12, 1021 - v9, rc.bottom - 77);
    else
        Lbl(app, kJpLblVolume, hdc, 12, 1016 - v9, rc.bottom - 77);

    if (app->FloatingWindow() == nullptr)
        HandlePaletteChanged2(hdc);                               // 0x42C140

    BitBlt(hdc, 6, 95, side - 10, 50,
           app->TimelineDC(), 0, 0, SRCCOPY);
    BitBlt(hdc, 6, 145, side - 25, rc.bottom - 393,
           app->PanelDC(), 0, 0, SRCCOPY);
    BitBlt(hdc, 8, rc.bottom - 135, 128, 128,
           app->CurveDC(), 0, 0, SRCCOPY);
    EndPaint(hwnd, &ps);

    app->state.messageSeen = 1;
    if (app->WindowLayoutReady() != 0)
        FrameDriver(app);                                         // 0x46B090

    // bone-list scrollbar refresh (SCROLLINFO embedded at this+2372)
    app->raw<std::int32_t>(offsets::kDwordScrollCb) = 28;
    app->raw<std::int32_t>(offsets::kDwordScrollFmask) = 7;        // SIF_ALL
    app->raw<std::int32_t>(offsets::kDwordScrollNmin) = 0;
    if (app->state.optflag0 == 0) {
        unsigned char* model = app->SelectedModel();
        app->raw<std::int32_t>(offsets::kDwordScrollNmax) =
            mikudancestudio::mdl::Mdl(model)->boneListRows - 3;
        app->raw<std::int32_t>(offsets::kDwordScrollNpos) =
            mikudancestudio::mdl::Mdl(model)->boneListPos;
    } else {
        app->raw<std::int32_t>(offsets::kDwordScrollNmax) =
            app->DisplayObjectListMatchCount() - 2;
        app->raw<std::int32_t>(offsets::kDwordScrollNpos) =
            app->DisplayObjectListScrollPosition();
    }
    const int page = (rc.bottom - 398) / 14 - 1;
    app->raw<std::int32_t>(offsets::kDwordScrollNmax) += page;
    app->raw<std::int32_t>(offsets::kDwordScrollNpage) = page;
    SetScrollInfo(GetDlgItem(hwnd, 427), SB_CTL,
                  reinterpret_cast<SCROLLINFO*>(app->at(2372)), TRUE);
}

}  // namespace mikudancestudio
